# Generated by Django 4.1.2 on 2022-10-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intitule", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Financement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intitule", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Partenaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("telephone", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Structure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sigle", models.CharField(max_length=100)),
                ("nom", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Travail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=10)),
                ("objet", models.TextField()),
                (
                    "nature",
                    models.CharField(
                        choices=[("CDI", "CDI"), ("CDD", "CDD")],
                        max_length=100,
                        verbose_name="naturecontrat",
                    ),
                ),
                ("matricule", models.CharField(max_length=10)),
                ("nom", models.CharField(max_length=60)),
                ("prenom", models.CharField(max_length=80)),
                ("montant", models.FloatField()),
                ("duree", models.CharField(max_length=10)),
                ("date_signature", models.DateField(auto_now_add=True)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("nombre_renouv", models.IntegerField()),
                ("date_renouvel", models.DateField()),
                ("date_resiliation", models.DateField()),
                ("lieu", models.CharField(max_length=100)),
                ("date_alerte", models.DateField()),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("file", models.FileField(upload_to="uploads_files/")),
            ],
        ),
    ]
