# Generated by Django 4.1.2 on 2022-10-20 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestioncontrat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="travail", name="date_resiliation",),
    ]
