# Generated by Django 4.1.3 on 2022-11-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gifs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("url", models.URLField()),
                ("nom_uploader", models.CharField(max_length=200)),
                ("created_at", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                (
                    "gifs",
                    models.ManyToManyField(
                        blank=True, related_name="gifs", to="gifs.gifs"
                    ),
                ),
            ],
        ),
    ]
