# Generated by Django 4.1.1 on 2022-09-30 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Famille",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_famille", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("pattes", models.IntegerField()),
                ("poids", models.FloatField()),
                ("taille", models.FloatField()),
                ("vitesse", models.FloatField()),
                (
                    "famille",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="info.famille"
                    ),
                ),
            ],
        ),
    ]
