# Generated by Django 4.1.2 on 2022-10-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Convention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=10)),
                ("objet", models.TextField()),
                ("nature", models.CharField(max_length=100)),
                ("matricule", models.CharField(max_length=10)),
                ("nom", models.CharField(max_length=60)),
                ("prenom", models.CharField(max_length=80)),
                ("montant", models.FloatField()),
                ("duree", models.CharField(max_length=10)),
                ("date_signature", models.DateField(auto_now_add=True)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("nombre_renouv", models.IntegerField()),
                ("date_renouvel", models.DateField()),
                ("lieu", models.CharField(max_length=100)),
                ("date_alerte", models.DateField()),
                ("file", models.FileField(blank=True, upload_to="uploads_files/")),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
            ],
        ),
    ]
