# Generated by Django 4.1.1 on 2022-11-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telephone", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personne",
            name="phone",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
