# Generated by Django 4.1.3 on 2022-11-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category", name="image", field=models.URLField(),
        ),
    ]
